backend:
  name: git-gateway
  branch: master
media_folder: ".vuepress/public/"
publish_mode: editorial_workflow 
preview_context: deploy-preview
show_preview_links: true 
public_folder: "../../"
display_url: https://exquisite-panda-66e029.netlify.app
collections:
  - name: pages
    label: Pages
    folder: "dist"
    create: true
    slug: "{{slug}}"
    preview_path: hitowa/{{year}}/{{month}}/{{title}}
    editor:
      preview: true

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}

     